version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - postgres_data:/var/lib/postgresql/dumps/
    env_file:
      - .env
  web:
    image: x038xx77/foodgram:v3.9.2021
    restart: always
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:1.19.6-alpine
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - static_volume:/code/static/
      - media_volume:/code/media/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    depends_on:
      - web
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
