# Generated by Django 3.0.5 on 2021-01-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='is_breakfast',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='is_dinner',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='is_lunch',
        ),
    ]
