# Generated by Django 3.0.5 on 2021-01-12 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameIngredient', models.CharField(max_length=200, verbose_name='Название')),
                ('unitsIngredient', models.CharField(max_length=20, verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngridient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.Ingredient')),
            ],
        ),
        migrations.RenameModel(
            old_name='Follow',
            new_name='FollowUser',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(default=None, help_text='Please enter your Text...', verbose_name='Название рецепта'),
        ),
        migrations.AddField(
            model_name='recipeingridient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='valueIngredient',
            field=models.ManyToManyField(through='recipes.RecipeIngridient', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.Ingredient', verbose_name='Ингридиенты'),
        ),
    ]
