# Generated by Django 3.0.5 on 2021-02-08 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrecipe',
            name='is_favore',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='is_purchases',
        ),
        migrations.AlterField(
            model_name='purchases',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoping_list', to='recipes.Recipe'),
        ),
    ]
