# Generated by Django 3.0.5 on 2021-01-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210117_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrecipe',
            old_name='recipe',
            new_name='following_recipe',
        ),
    ]
