# Generated by Django 3.0.5 on 2021-01-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210130_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unit',
            new_name='UnitIngredients',
        ),
        migrations.RenameField(
            model_name='unitingredients',
            old_name='dimension',
            new_name='dimension_unit',
        ),
    ]
