# Generated by Django 3.0.5 on 2021-01-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210118_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrecipe',
            old_name='following_recipe',
            new_name='author',
        ),
    ]
