# Generated by Django 3.0.5 on 2021-01-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210117_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrecipe',
            old_name='following_recipe',
            new_name='recipe',
        ),
    ]
