# Generated by Django 3.0.5 on 2021-02-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210208_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='checkbox_style',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
