# Generated by Django 3.0.5 on 2021-01-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210120_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrecipe',
            old_name='author',
            new_name='following_recipe',
        ),
        migrations.RenameField(
            model_name='followuser',
            old_name='following',
            new_name='author',
        ),
    ]
