# Generated by Django 3.0.5 on 2021-01-17 12:42

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.list


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210117_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipesView',
            fields=[
                ('diet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.Diet')),
            ],
            bases=('recipes.diet', django.views.generic.list.ListView),
        ),
    ]
