# Generated by Django 3.0.5 on 2021-01-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210114_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followuser',
            old_name='author',
            new_name='recipe',
        ),
        migrations.DeleteModel(
            name='FollowRecipe',
        ),
    ]
