# Generated by Django 3.0.5 on 2021-01-18 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipesview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrecipe',
            old_name='recipe',
            new_name='following_recipe',
        ),
        migrations.DeleteModel(
            name='RecipesView',
        ),
    ]
