# Generated by Django 3.0.5 on 2021-01-21 23:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210121_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_unit',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=True),
        ),
    ]
