# Generated by Django 3.0.5 on 2021-01-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210114_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrecipe',
            name='obj',
            field=models.BooleanField(default=False),
        ),
    ]
