# Generated by Django 3.0.5 on 2021-01-15 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_followrecipe_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_recipe', to='recipes.Recipe'),
        ),
    ]
