# Generated by Django 3.0.5 on 2021-01-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_recipe_ingredients_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='ingredients_unit',
            field=models.CharField(max_length=200),
        ),
    ]
