# Generated by Django 3.0.5 on 2021-01-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20210122_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrecipe',
            old_name='follow_recipe',
            new_name='following_recipe',
        ),
    ]
