# Generated by Django 3.0.5 on 2021-01-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210122_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='diet',
        ),
        migrations.AddField(
            model_name='recipe',
            name='diet',
            field=models.ManyToManyField(related_name='diet', to='recipes.Diet', verbose_name='рацион'),
        ),
    ]
