# Generated by Django 3.0.5 on 2021-01-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20210122_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=models.ManyToManyField(blank=True, related_name='diet', to='recipes.Diet', verbose_name='рацион'),
        ),
    ]
