# Generated by Django 3.0.5 on 2021-01-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20210122_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=models.ManyToManyField(blank=True, related_name='recipe', to='recipes.Diet', verbose_name='рацион'),
        ),
    ]
