# Generated by Django 3.0.5 on 2021-01-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20210123_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diet',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='followrecipe',
            old_name='obj',
            new_name='is_favore',
        ),
    ]
